### PR TITLE
More project examples

### PR DESCRIPTION
**Pull request by mwz**
Includes Sbt and Maven single and multi-module projects, related to #41.

### CODE REVIEW

**Comment by BalmungSan** [comment]
Hello @mwz, +1: for adding those examples. Just one thing, bump **SBT** to `1.1.5`.

Also, I was wondering if it would be worth to add Java sources to the examples?

**Comment by mwz** [comment]
> Hello @mwz, 👍 for adding those examples. Just one thing, could you bump SBT to 1.1.5?

Done in c2f43f5.

> Also, I was wondering if would be worth to add Java sources to the examples?

To be honest I'm not too keen on having Java sources in the examples as we're focusing on Scala projects, but maybe we could at least create a new issue and see if there is any interest or if we get any enquires about mixed Scala-Java projects? Would you be happy with that for now?

**Comment by BalmungSan** [comment]
Yes, to be honest I only proposed that to ensure we don't break the expected behavior of the plugin when the `sonar.sources` property have multiple paths.
But I guess it doesn't have to much sense right now, because we don't run tests against the example projects yet.

Anyway, I think this is ready to be merged :+1:

**Comment by mwz** [comment]
Oh yes, that's a good shout. 👌 
Ok, let me merge this one and I'll have a go at a mixed scala-java project.

**Pull request merged**
