### PR TITLE
Strip out prefix from scoverage filenames.

### LINKED ISSUE #56: The file has no scoverage information associated with it.
We're using version 6.2.0 of the plugin, but when running the sonarqube task from Gradle it seems that it somehow fails to parse the scoverage.xml report, even though it finds it and loads it successfully.

These are the errors I am seeing:

[scoverage] Initializing the scoverage sensor.
[scoverage] Successfully loaded the scoverage report file: 'C:\Users\dmarkhas\IdeaProjects\sdk-base\build\reports\scoverage\scoverage.xml'.
[scoverage] The file: 'src/main/scala/com/intel/daas/sdk/Launcher.scala' has no scoverage information associated with it.
[scoverage] The file: 'src/main/scala/com/intel/daas/sdk/application/AbstractSparkApplication.scala' has no scoverage information associated with it.
[scoverage] The file: 'src/main/scala/com/intel/daas/sdk/application/ApplicationContext.scala' has no scoverage information associated with it.

I saw #51 but in this case the filenames match exactly the filenames in the xml report so I'm not sure what's wrong. I've attached the scoverage report (had to rename from .xml to .txt for GitHub) - anything obvious I am missing perhaps?

[scoverage.txt](https://github.com/mwz/sonar-scala/files/1979771/scoverage.txt)

### PR DESCRIPTION
**Pull request by mwz**
Attempts to fix #56.

I'll add some scoverage specific tests when I get some free time tomorrow.

@BalmungSan, @dmarkhas

### CODE REVIEW

**Comment by BalmungSan** [comment]
Hey @mwz, nice work. Hope we don't have any further problems with the scoverage filenames.

I was thinking that we should fix the incompatibility with Windows in this PR too. What do you think?
Maybe this is enough for fix it?
```scala
scoverageFilename = Paths.get((classNode \@ "filename").replace(java.io.File.separatorChar, '/'))
```

**Comment by mwz** [comment]
Hi @BalmungSan, I'm not sure about Windows compatibility and to be honest with you I'm quite reluctant to make any changes like "find `\` and replace with `/`" simply because I don't have a way of testing these and I'm also not entirely convinced that this is the right approach.

I'd be still open to investigating this, but probably in a separate issue - are you ok with that?

**Comment by BalmungSan** [comment]
Hi @mwz, I completely agree that it would be best to investigate it in a separate issue, because the more I think of it, the more problems and changes I noticed. So it won't be as simple as I first thought.

But I still think we should prioritize it. And for the testing, I suppose the only way would be to run it in a windows machine.

**Comment by mwz** [comment]
Ok, I've added a scoverage report parsing test in 5ab9cca and this PR is ready for a final review. Let me know @BalmungSan if you're happy with this getting merged.

**Comment by dmarkhas** [comment]
FWIW I've tested this on our Linux Jenkins slaves and it works well 👍

**Comment by BalmungSan** [comment]
> @BalmungSan could you let me know if you're happy with this getting merged.
@mwz Absolutely.

> FWIW I've tested this on our Linux Jenkins slaves and it works well 👍
@dmarkhas I'm really happy for that 👍 😄.

@mwz you should make a release after merging this.

**Pull request merged**
