### PR TITLE
Added scapegoat report path to the example sbt projects.

### PR DESCRIPTION
**Pull request by mwz**
Related to #82.

### CODE REVIEW

**Comment by mwz** [comment]
Yes, I think I'll set up a new example project with some ugly issues in a separate PR.

**Comment by BalmungSan** [comment]
Uhm.. ok, why not in the same example projects we already have?

**Comment by mwz** [comment]
I think I would prefer not to pollute the examples too much with any bad practices, thus the idea of setting up up another example project with some deliberate issues, although, just thinking about it, maybe we should be consistent and introduce the same set of issues into every example project for testing purposes so we can make sure that we get the same results from running the analysis on each project.

**Comment by BalmungSan** [comment]
I'm in favor of being consistent in each example, and use the examples not only for showing how to configure each build tool, but also for testing the desired behavior of the plugin.

**Comment by BalmungSan** [comment]
Yes, go ahead. 😃

**Pull request merged**
