### PR TITLE
Fix Gradle to 5.2.1.

### PR DESCRIPTION
**Pull request by mwz**
I can't get the gradle-scalatest plugin (used in the example projects) to work with Gradle 5.3, so I've fixed the version to 5.2.1 until https://github.com/maiflai/gradle-scalatest/issues/77 gets resolved.

### CODE REVIEW

**Comment by BalmungSan** [comment]
Cool, we should do the same with **Maven**.

**Comment by mwz** [comment]
The latest version of Maven works ok, so there's probably no need to do this.

**Comment by BalmungSan** [comment]
I mean, just to be consistent.
In **SBT** we have the `project/build.properties` file to set the version.
With **Maven** & **Gradle** one has to use the wrappers, since you already added the one from Gradle, I think we should do the same with Maven.
That would also make more easy to ensure everything works fine on local.

**Comment by mwz** [comment]
You're right, it makes sense to do it for consistency reasons.

**Pull request merged**
