### PR TITLE
Add a feature flag to the Scoverage Sensor

### LINKED ISSUE #81: Scoverage feature flag

### PR DESCRIPTION
**Pull request by BalmungSan**
Fixes #81

### CODE REVIEW

**Comment by mwz** [comment]
You're on fire - thanks for the PR, I'll review all of them later today.

**Comment by BalmungSan** [comment]
> "You're on fire".

Hahahaha 😎 

It has been a quite week, took the opportunity to help as much as possible! now - Sine, next week will start a new project, so I may be _"out of game"_ for a while...

**Comment by mwz** [comment]
Looks good to me; can you think of any particular reason one might want to disable this sensor?

**Comment by BalmungSan** [comment]
> "can you think of any particular reason one might want to disable this sensor?"

To be honest, no. In the sense that I also do not see any _"reason"_ to disable any other sensor.
But, since we had been adding feature flags to all of them, it seems to me that we should be standard.

On the other hand, maybe if you need to add some hotfix really fast to production, but it reduces the coverage enough to make your CI build to fail, mauve disabling this sensor would be _"good"_, since sonar will return the coverage of the previous scan...
Or maybe someone only want coverage information from jUnit instead of from Scoverage, who knows.

**Comment by mwz** [comment]
Yeah, since we allow to disable other sensors it makes sense to be consistent and also allow to disable this one in case anyone wants to do that.

**Pull request merged**
